#!/usr/bin/env bash
# Configures a new Ubuntu machine to install nginx and set up a 301 redirect on /redirect_me

sudo apt-get update -y
sudo apt-get install nginx -y

echo "Holberton School" > /var/www/html/index.html

sudo sed -i 's|server_name _;|server_name _;\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}|' /etc/nginx/sites-available/default

sudo service nginx restart
